export const environment = {
  production: true,
  i18n: {
    search: 'Buscar',
    emojilist: 'Lista de emojis',
    notfound: 'No se encontro emojis',
    clear: 'Limpiar',
    categories: {
      search: 'Resultados de la busqueda',
      recent: 'Uso Frecuente',
      people: 'Smileys & Personas',
      nature: 'Animales & Naturaleza',
      foods: 'Comidas & Bebidas',
      activity: 'Actividades',
      places: 'Viajes & Lugares',
      objects: 'Objetos',
      symbols: 'Símbolos',
      flags: 'Banderas',
      custom: 'Personalizados',
    },
    skintones: {
      1: 'Default Skin Tone',
      2: 'Light Skin Tone',
      3: 'Medium-Light Skin Tone',
      4: 'Medium Skin Tone',
      5: 'Medium-Dark Skin Tone',
      6: 'Dark Skin Tone',
    },
  },
};
